### ISSUE TITLE
Data Processing

### ISSUE THREAD

**Issue by epikjjh** [HyOsori/NBA_Result_Predictor#1]
정민 후배님 필요한 Data들은 모두 Crawling 완료하였는데, Data processing에 대해서는 이번주에 조금 더 논의가 필요할 것 같습니다. 일단 Neural network 구현에 집중하는 것이 좋을 것 같습니다.

**Comment by parkjuida** [comment]
혹시 Neural network는 어떤 모델을 사용할 계획이신가요??

**Comment by epikjjh** [comment]
일단 layer는 대략적으로 personal - team - division 크게 3단계를 거치려고 생각중입니다.
